---
- name: Drop inventory template
  template:
    src: templates/inventory_hosts.j2
    dest: /home/ubuntu/express/inventory/hosts
    mode: '0644'

- name: Drop management plane template
  template:
    src: templates/pf9-express.conf.j2
    dest: /home/ubuntu/express/pf9-express.conf
    mode: '0644'

- name: Create private key file
  copy:
    dest: "/root/.ssh/id_rsa"
    content: "{{ hostvars['localhost'].keypair.key.private_key }}"
    mode: '0600'

- name: Install express prereqs
  args:
    chdir: /home/ubuntu/express/
  command: ./pf9-express -i

- name: Install express
  args:
    chdir: /home/ubuntu/express/
  command: ./pf9-express -a pmo
